# H96 Max M9S - Rockchip RK3576
BOARD_NAME="H96 Max M9S"
BOARD_VENDOR="h96"
BOARDFAMILY="rk35xx"

KERNEL_TARGET="vendor,edge"
FULL_DESKTOP="no"
BOOT_LOGO="desktop"

BOOT_FDT_FILE="rockchip/rk3576-evb1-v10.dtb"
BOOT_SCENARIO="spl-blobs"
IMAGE_PARTITION_TABLE="gpt"

BOARD_MAINTAINER=""
INTRODUCED="2026"
